### PR TITLE
Add Leiningen support

### PR DESCRIPTION
**Pull request by eddumelendez**
Support [Leiningen](https://leiningen.org/) in order to build
[Clojure](https://clojure.org/) services.

### CODE REVIEW

**Comment by eddumelendez** [comment]
I was able to create the buildpack locally. See logs [here](https://gist.github.com/eddumelendez/dd3b1cf3fe5bc66aa12395d2126cc9b8)

**Comment by eddumelendez** [comment]
about [this commit](https://github.com/GoogleCloudPlatform/buildpacks/pull/97/commits/5fe80b9a235f2c6f50bf93a0c390abc0a0e2778c), it would be cool if we can set the jar path in the buildpack using toml so the patterns can apply independently.

**Comment by briandealwis** [comment]
Hi @eddumelendez.  Thank you for your submission.  The team discussed the PR and we have a general reluctance to take on support for builders that none of us use.  We've been down this road on other projects and it rarely ends well :disappointed:

What we should think about it how to support additional builders, such as SBT and Leiningen.  A further complication is how to incorporate such additional builders into the devmode support.  We'll be revisiting this soon, I hope, and will keep Leiningein in mind.  We'll be in touch.

**Comment by jamesward** [comment]
The [Buildpack Registry](https://registry.buildpacks.io) aims to be a good place for community-supported Buildpacks like this one.  Another option is to shim your buildpack onto the Google ones, like:
https://github.com/jamesward/gcloud-buildpack

**Pull request closed without merging**
